const canvasConstants = {
  RESOLUTION: 2,
  GRID_DEFAULT_WIDTH: 200,
  GRID_DEFAULT_HEIGHT: 10,
  CANDLE_DEFAULT_WIDTH: 100,
  CANDLE_DISTANCE_DEFAULT: 135,
  SCALE_Y_DEFAULT: 5,
  LEFT_RULER_WIDTH_DEFAULT: 80,
}

export default canvasConstants;