kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: rancher.io/local-path
parameters:
  type: ssd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true